[package]
name = "mb"
version = "0.3.0"
description = "Build automation tool"
authors = ["Johannes Asal"]
license = "MIT"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4.1.6", features = ["derive"] }
colored = "2"
dirs = "4"
dunce = "1"
figment = { version = "0.10", features = ["toml", "env", "test"] }
flate2 = "1"
git2 = "0.16.1"
glob = "0.3"
once_cell = "1"
path-absolutize = "3.0.14"
path-slash = "0.2.1"
regex = "1"
reqwest = { version = "0.11", features = ["blocking", "rustls-tls-native-roots"] }
rune = "0.12.1"
rune-modules = { version = "0.12.1", features = ["http", "io"] }
self_update = "0.36"
serde = { version = "1", features = ["derive"] }
tar = "0.4"
tempfile = "3"
tera = "1"
toml = "0.7"
yaml-rust = "0.4"

[dev-dependencies]
futures-executor = "0.3"
thiserror = "1"

[profile.release]
opt-level = "z"
strip = true
lto = true