name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: "${{ matrix.os.name }} ${{ matrix.test.name }} (${{ matrix.toolchain }})"
    continue-on-error: false
    runs-on: ${{ matrix.os.host }}
    container: ${{ matrix.os.container }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - { name: Linux-Debian-buster, host: ubuntu-latest, container: "rust:slim-buster" }
          - { name: Linux-Debian-bullseye, host: ubuntu-latest, container: "rust:slim-bullseye" }
          - { name: Linux-Alpine-3.16, host: ubuntu-latest, container: "rust:alpine3.16" }
          - { name: Windows, host: windows-latest, container: null }
        toolchain: [nightly, stable]

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true
      
      - name: Install build requirements
        if: matrix.os.container != 'rust:alpine3.16' && matrix.os.host != 'windows-latest'
        run: |
          apt-get update
          apt-get install -y libssl-dev pkg-config
      
      - name: Install build requirements
        if: matrix.os.container == 'rust:alpine3.16'
        run: |
          apk update
          apk add openssl-dev pkgconfig

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test