name: Release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      packages: write
      pull-requests: read
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: mb
            asset_name: mb-${{ github.ref }}-linux-x86_64
          - os: windows-latest
            artifact_name: mb.exe
            asset_name: mb-${{ github.ref }}-windows-x86_64.exe

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --locked
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}