name: Release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:
  windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: cargo test --release
      - name: Build
        run: cargo build --release
      - name: Upload executable
        run: |
          cp ./target/release/mb.exe ./metabuild-${GITHUB_REF##*/}-windows-x86_64.exe
          ./.github/workflows/upload_asset.sh \
            ./metabuild-${GITHUB_REF##*/}-windows-x86_64.exe $GITHUB_TOKEN

  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: cargo test --release
      - name: Build
        run: cargo build --release
      - name: Upload executable
        run: |
          cp ./target/release/mb ./metabuild-${GITHUB_REF##*/}-linux-x86_64
          ./.github/workflows/upload_asset.sh \
            ./metabuild-${GITHUB_REF##*/}-linux-x86_64 $GITHUB_TOKEN