name: Release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      packages: write
      pull-requests: read
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            artifact_name: mb
            asset_name: mb-${{ github.ref_name }}-linux-x86_64-openssl1
          - os: ubuntu-22.04
            artifact_name: mb
            asset_name: mb-${{ github.ref_name }}-linux-x86_64-openssl3
          - os: windows-latest
            artifact_name: mb.exe
            asset_name: mb-${{ github.ref_name }}-windows-x86_64.exe

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --locked
    - name: Build Windows installer
      if: matrix.os == 'windows-latest'
      run: |
        cargo install cargo-wix
        cargo wix
        "${{ github.ref_name }}" -match '^v([0-9]+\.[0-9]+\.[0-9]+).*'
        $version=$Matches.1
        echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
    - name: Upload Windows installer to release
      uses: svenstaro/upload-release-action@v2
      if: matrix.os == 'windows-latest'
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/wix/mb-${{ env.BUILD_VERSION }}-x86_64.msi
        asset_name: metabuild-${{ github.ref_name }}-x86_64.msi
        tag: ${{ github.ref }}
