name: Release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish-linux:
    runs-on: ubuntu-latest
    container: "alpine:3.16"
    
    permissions:
      contents: write
      packages: write
      pull-requests: read
    
    steps:
      - uses: actions/checkout@v3
      - name: Install prerequisites
        run: |
          apk update
          apk add build-base perl curl

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: x86_64-unknown-linux-musl
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --locked --target x86_64-unknown-linux-musl

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/x86_64-unknown-linux-musl/release/mb
          asset_name: mb-${{ github.ref_name }}-x86_64-unknown-linux-musl
          tag: ${{ github.ref }}
  
  publish-windows:
    runs-on: windows-latest

    permissions:
      contents: write
      packages: write
      pull-requests: read

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --locked --target x86_64-pc-windows-msvc
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/x86_64-pc-windows-msvc/release/mb.exe
        asset_name: mb-${{ github.ref_name }}-x86_64-pc-windows-msvc.exe
        tag: ${{ github.ref }}
