name: Release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish-linux:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        include:
          - container: "rust:buster-slim"
            asset_name: mb-${{ github.ref_name }}-linux-x86_64-debian-buster
          - container: "rust:bullseye-slim"
            asset_name: mb-${{ github.ref_name }}-linux-x86_64-debian-bullseye
          - container: "rust:alpine3.16"
            asset_name: mb-${{ github.ref_name }}-linux-x86_64-alpine-3.16
    
    container:
      image: ${{ matrix.container }}
    
    permissions:
      contents: write
      packages: write
      pull-requests: read
    
    steps:
      - uses: actions/checkout@v3
      - name: Build
        if: matrix.container != 'rust:alpine3.16'
        run: |
          apt-get update
          apt-get install -y libssl-dev pkg-config
          cargo build --release --locked
      - name: Build
        if: matrix.container == 'rust:alpine3.16'
        run: |
          apk update
          apk add openssl-dev pkgconfig
          cargo build --release --locked
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/mb
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
  
  publish-windows:
    runs-on: windows-latest

    permissions:
      contents: write
      packages: write
      pull-requests: read

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --locked
    - name: Build Windows installer
      run: |
        cargo install cargo-wix
        cargo wix
        "${{ github.ref_name }}" -match '^v([0-9]+\.[0-9]+\.[0-9]+).*'
        $version=$Matches.1
        echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/mb.exe
        asset_name: mb-${{ github.ref_name }}-windows-x86_64.exe
        tag: ${{ github.ref }}
    - name: Upload Windows installer to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/wix/mb-${{ env.BUILD_VERSION }}-x86_64.msi
        asset_name: metabuild-${{ github.ref_name }}-x86_64.msi
        tag: ${{ github.ref }}
